server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.241.164:3306/cloud?useUnicode=true&character=utf-8&useSSL=false
    username: root
    password: nuttertools

mybatis:
  mapperLocations: class:mapper/*.xml
  type-aliases-package: com.zero.springcloud.entity #entitys所在包